### ISSUE TITLE
Bug product-summary-sku-selector

### ISSUE THREAD

**Issue by stellassantos** [vtex-apps/product-summary#297]
**Describe the bug**
O sku-selector não esta trocando a imagem quando clicado, mas se entro no produto ele vai para o link correto.

**To Reproduce**

1. Go to 'https://shoulderio.myvtex.com/roupas/blusas/'
2. Click on 'product-summary-sku-selector'
3. See error

**Expected behavior**
Que ao clicar no sku-selector, ja selecionasse e mudasse diretamente na vitrine, sem precisar entrar na pdp.

**Screenshots**
https://monosnap.com/file/q2WuSwmbIhSt88vLPwLg8TSXF1vBS9

**Additional context**
No nosso vendor anterior, funcionava perfeitamente o sku-selector 
https://shoulderdevs2--shoulder.myvtex.com/
https://monosnap.com/file/ipxcPyiIOMklMaT2sHKRMSOqAaFd1l

**Comment by hugocostadev** [comment]
Estamos com este mesmo problema também! Relatamos nesta Issue https://github.com/vtex-apps/store-discussion/issues/516 .

**Comment by pscruzzz** [comment]
Hello everyone! Got this issue fixed in my workspace by adding "__unstableProductOriginVtex": true as a prop to my store.search blocks (also added to store.search#brand , store.search#department and so on). As Thalyta said (in the above mentioned issue), this is a temporary prop, that will help you out until it's fixed!

CC: @stellassantos

**Comment by stellassantos** [comment]
Funcionou, muito brigada Pedro!
